env:
  node: true
  commonjs: true
  es6: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-console: off
  quotes: 
    - error
    - single
  no-unused-vars: error
  indent: 
    - error
    - 2
    - { SwitchCase: 1 }
  object-curly-spacing:
    - error
    - always
    - { arraysInObjects: false, objectsInObjects: false }
  space-before-function-paren:
    - error
    - always
  keyword-spacing: error
  space-before-blocks: error
  no-multiple-empty-lines: 
    - error
    - { max: 1}
  semi: 
    - error
    - always
  eol-last:
    - error
    - always
overrides: 
  - files: "*.json"
    rules: 
      quotes: [error, double]
      semi: off