name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test
      - name: generate test coverage
        run: npm run coverage
        # TODO: enable this step when tests are implemented
      - name: codacy coverage report
        if: false
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
